import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/navbar";
import Footer from "@/components/ui/footer";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shopping Website",
  description: "Generated by create next app",
};

export default function RootLayout(
  {
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="max-w-[90%] mx-auto">
          <Providers>
        <Navbar/>
        {children}
        </Providers>
        </div>
         <Footer/>  
        </body>
    </html>
  );
}
